<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Search</name>
   <tag></tag>
   <elementGuidId>6741f72c-b4da-4994-a15d-26dab164aa6b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[4]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li > button.btn-primary.igx-button--flat</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>2c8e7483-348a-491e-ab2d-b6cce5a061a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b9324382-9128-4c67-8a44-a6b91f91007f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>2a261833-982d-48d1-bd34-b6f8b52047e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn-primary igx-button--flat</value>
      <webElementGuid>2302799d-ba70-458d-aa37-719b77c436cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ca3546d2-e5b5-42d7-91ff-000069b37896</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>1da4cfff-bf9b-400b-9b50-c6a4ceaac4c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;igx-drop-down-item-2&quot;)/span[@class=&quot;igx-drop-down__inner&quot;]/div[@class=&quot;content-holder ssi-filter w-100&quot;]/div[@class=&quot;filter-footer&quot;]/div[@class=&quot;btn-holder&quot;]/ul[@class=&quot;btnlist&quot;]/li[1]/button[@class=&quot;btn-primary igx-button--flat&quot;]</value>
      <webElementGuid>561bb159-cf34-4b5c-b118-a577f97e81dc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[4]</value>
      <webElementGuid>f69388b9-bfa3-48aa-9a6c-919b9a3d53f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//igx-drop-down-item[@id='igx-drop-down-item-2']/span/div/div[2]/div/ul/li/button</value>
      <webElementGuid>36b8cef8-120f-4810-8fa7-52a1c1df89bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/button</value>
      <webElementGuid>e02742bb-f445-44f5-8f64-b8a0b53d3bfd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @title = 'Search' and (text() = 'Search' or . = 'Search')]</value>
      <webElementGuid>8b46a359-93ee-4fa7-92e7-b147219afe43</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
