<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_CODE_txtCode</name>
   <tag></tag>
   <elementGuidId>f6bf274c-9779-42c7-93dd-a5d64839c668</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='txtCode']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;txtCode&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>90613a59-47f0-4b43-96f7-9daf8ad349d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txtCode</value>
      <webElementGuid>68c92bd0-f14d-4462-8bce-929dcbe02550</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d6c23a17-7bac-4fb6-b2e8-a982d23b7c00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>ffcfdde8-ea8d-495e-b17e-912ea51ccaa7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>igx-input-group__input ng-star-inserted</value>
      <webElementGuid>ef206087-9506-468d-9c2a-6076225ac83b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;igx-input-group-2&quot;)/div[@class=&quot;igx-input-group__bundle ng-star-inserted&quot;]/div[@class=&quot;igx-input-group__bundle-main&quot;]/input[@class=&quot;igx-input-group__input ng-star-inserted&quot;]</value>
      <webElementGuid>6ce0e036-f682-4bd7-a10a-e9894daa17de</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='txtCode']</value>
      <webElementGuid>a1908931-0751-4ce2-83b1-2f96f91cfea2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//igx-input-group[@id='igx-input-group-2']/div/div/input</value>
      <webElementGuid>14600186-0774-4d78-b560-d3e3acaacaa1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/igx-input-group/div/div/input</value>
      <webElementGuid>2a108ad9-3fe7-4f94-8200-b2746f99b85c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'txtCode' and @type = 'text']</value>
      <webElementGuid>1b576227-a51e-429f-848e-e253b260b546</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
