<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_NAME_txtName</name>
   <tag></tag>
   <elementGuidId>3047f7d1-44f4-4ea7-8db9-c207fd777801</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='txtName']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;txtName&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c4dcb4c1-8f08-413c-bde6-f75d17dd2e24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txtName</value>
      <webElementGuid>af4e7557-3a5e-4b96-98f6-31013b12c12d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7f3701d8-9864-47ba-899d-f9ed30ac67eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>7bd713e0-a833-4c71-8f6b-61ec15ac510b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>igx-input-group__input ng-star-inserted</value>
      <webElementGuid>ee969aae-a676-46b7-a729-f2137317016b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;igx-input-group-3&quot;)/div[@class=&quot;igx-input-group__bundle ng-star-inserted&quot;]/div[@class=&quot;igx-input-group__bundle-main&quot;]/input[@class=&quot;igx-input-group__input ng-star-inserted&quot;]</value>
      <webElementGuid>a6d144db-f4bb-4293-91a3-3abdbf5efb63</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='txtName']</value>
      <webElementGuid>f0177d55-a683-47a9-80a8-8bc00a1f62c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//igx-input-group[@id='igx-input-group-3']/div/div/input</value>
      <webElementGuid>cf7c0787-f7ed-4c48-829d-798dc7e3cfc9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/igx-input-group/div/div/input</value>
      <webElementGuid>fdf48496-4ccd-44ce-a3fb-9092453270aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'txtName' and @type = 'text']</value>
      <webElementGuid>1b9d712e-fd72-4f1c-b637-8b8a8675b613</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
