<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_expand_more</name>
   <tag></tag>
   <elementGuidId>389fe41d-ede9-4295-a100-9c7b4bab0e5e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//igx-grid[@id='FWLookupGrid']/igx-grid-toolbar/div/lib-ssi-filter/div/div[2]/div[2]/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.icon-hlder</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>809c0252-9005-435b-8fee-1bced1c22643</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Advance Search</value>
      <webElementGuid>3d3ea91b-b2f1-469a-930d-501311d4ca47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon-hlder</value>
      <webElementGuid>bb5bb207-179e-4fa0-abad-c4b538b32852</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>expand_more</value>
      <webElementGuid>ef953327-e629-43d0-be5d-5cc5728a4ff5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;FWLookupGrid&quot;)/igx-grid-toolbar[@class=&quot;igx-grid-toolbar ng-star-inserted&quot;]/div[@class=&quot;igx-grid-toolbar__custom-content ng-star-inserted&quot;]/lib-ssi-filter[@class=&quot;filter ng-star-inserted&quot;]/div[@class=&quot;filter-area ssi-filter&quot;]/div[@class=&quot;filter-holder&quot;]/div[@class=&quot;pull-down&quot;]/span[@class=&quot;icon-hlder&quot;]</value>
      <webElementGuid>18f7074e-eb8b-43c5-aa38-3e72188ad6c0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//igx-grid[@id='FWLookupGrid']/igx-grid-toolbar/div/lib-ssi-filter/div/div[2]/div[2]/span</value>
      <webElementGuid>5bcd5615-9a40-466b-8a31-36c9f3e94bdb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/span</value>
      <webElementGuid>8e4ea8dd-6f35-47eb-89cf-359d4199ccd6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@title = 'Advance Search' and (text() = 'expand_more' or . = 'expand_more')]</value>
      <webElementGuid>515f36b6-4f9c-4aed-ad93-1dfb822e4964</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
