<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Name</name>
   <tag></tag>
   <elementGuidId>c8bece8f-a488-4dc2-b7ca-7615b6f10cb8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//igx-grid-header-group[@id='FWLookupGrid_-1_0_2']/igx-grid-header/span/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#FWLookupGrid_-1_0_2 > igx-grid-header.igx-grid__th.igx-grid__th--fw.igx-grid__th--sortable.igx-drag.igx-drag--select-disabled.ng-star-inserted > span.igx-grid__th-title > span.ng-star-inserted</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>c290f542-4b33-4b3f-b370-55cf4b4a06e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Name</value>
      <webElementGuid>04dbef12-5323-4a71-a783-e7948584e12f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-star-inserted</value>
      <webElementGuid>284a3dc8-e161-4567-8413-a7893d0f0a47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Name</value>
      <webElementGuid>0aba1818-c08e-4baf-be7b-e2df9eba31a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;FWLookupGrid_-1_0_2&quot;)/igx-grid-header[@class=&quot;igx-grid__th igx-grid__th--fw igx-grid__th--sortable igx-drag igx-drag--select-disabled ng-star-inserted&quot;]/span[@class=&quot;igx-grid__th-title&quot;]/span[@class=&quot;ng-star-inserted&quot;]</value>
      <webElementGuid>4fda569a-1dc6-45e7-9521-330fd6522e36</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//igx-grid-header-group[@id='FWLookupGrid_-1_0_2']/igx-grid-header/span/span</value>
      <webElementGuid>59cceec5-2ef4-4690-baff-873d17644d08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//igx-grid-header-group[2]/igx-grid-header/span/span</value>
      <webElementGuid>08badc6c-5b6b-4b53-adce-77c5044297c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@title = 'Name' and (text() = 'Name' or . = 'Name')]</value>
      <webElementGuid>99d7fc02-a404-4ab9-b713-729446f92f56</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
