<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Modified On</name>
   <tag></tag>
   <elementGuidId>c4303aae-957d-454d-9ceb-2dfaaa2e69e6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//igx-grid-header-group[@id='FWLookupGrid_-1_0_12']/igx-grid-header/span/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#FWLookupGrid_-1_0_12 > igx-grid-header.igx-grid__th.igx-grid__th--fw.igx-grid__th--sortable.igx-drag.igx-drag--select-disabled.ng-star-inserted > span.igx-grid__th-title > span.ng-star-inserted</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>28b63b89-4508-4c23-a153-39bbb750838c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Modified On</value>
      <webElementGuid>d90d2171-e40b-4f8f-9fe3-3c42ed7fb0db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-star-inserted</value>
      <webElementGuid>70b1292a-6a2d-4fbe-aa71-58bfb5f742ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Modified On</value>
      <webElementGuid>9b3337c6-a042-43f3-959c-8119dbd05f5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;FWLookupGrid_-1_0_12&quot;)/igx-grid-header[@class=&quot;igx-grid__th igx-grid__th--fw igx-grid__th--sortable igx-drag igx-drag--select-disabled ng-star-inserted&quot;]/span[@class=&quot;igx-grid__th-title&quot;]/span[@class=&quot;ng-star-inserted&quot;]</value>
      <webElementGuid>3743023c-8c8a-4a91-9d38-1e80d21c33d8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//igx-grid-header-group[@id='FWLookupGrid_-1_0_12']/igx-grid-header/span/span</value>
      <webElementGuid>b8f02c9d-725e-4102-aa0e-0afa8957e593</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//igx-grid-header-group[8]/igx-grid-header/span/span</value>
      <webElementGuid>eed3df9c-aa2d-4170-904f-0885ba837ba1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@title = 'Modified On' and (text() = 'Modified On' or . = 'Modified On')]</value>
      <webElementGuid>a4800792-a358-4b1f-bac4-b8d47ce1dd64</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
