<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>igx-icon_arrow_drop_down</name>
   <tag></tag>
   <elementGuidId>2f1b001f-7948-45c4-bab0-787560926af1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//igx-icon[@id='igx-icon-17']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#igx-icon-17</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>igx-icon</value>
      <webElementGuid>9075f39f-d098-4e50-b368-387b78ffb912</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fontset</name>
      <type>Main</type>
      <value>material</value>
      <webElementGuid>83c2782a-1132-49d5-9e3e-38cd4a0c3e81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>material-icons igx-icon ng-star-inserted</value>
      <webElementGuid>90b2415c-8530-49ea-9051-7d85e6a44dfe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>087f907d-7d96-4feb-b4cf-dadef50848cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>igx-icon-17</value>
      <webElementGuid>74f0d115-73e4-4797-ae46-44498465a9b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> arrow_drop_down </value>
      <webElementGuid>a470431d-a4ed-4d00-b1d2-1752925c5b19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;igx-icon-17&quot;)</value>
      <webElementGuid>e2d877c5-90de-4d96-8cea-cade1242e584</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//igx-icon[@id='igx-icon-17']</value>
      <webElementGuid>c4422563-c550-465d-a1cf-52a5edc0b2ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//igx-input-group[@id='igx-input-group-15']/div/igx-suffix/igx-icon</value>
      <webElementGuid>604c1f2c-b8c1-4e0d-b743-15f1924d3600</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/lib-ssi-select/div/igx-combo/igx-input-group/div/igx-suffix/igx-icon</value>
      <webElementGuid>e281ac19-3512-4de0-90b1-2841c4134bcb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//igx-icon[@id = 'igx-icon-17' and (text() = ' arrow_drop_down ' or . = ' arrow_drop_down ')]</value>
      <webElementGuid>6cdffa9e-9dac-4698-80d3-7e3d8ae08118</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Category'])[1]/following::igx-icon[1]</value>
      <webElementGuid>a1bf8bfa-5113-4c34-a2f3-4fbc677571b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Name'])[1]/following::igx-icon[1]</value>
      <webElementGuid>4f6120ab-0739-431b-af4f-47f944fae4ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Parent Category'])[1]/preceding::igx-icon[1]</value>
      <webElementGuid>d0dad4c9-7702-481c-8ee1-46977fb93af0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Value'])[1]/preceding::igx-icon[2]</value>
      <webElementGuid>7cdf1a46-90b8-41a6-acd0-9d10e7d82323</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
