<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Name_Name</name>
   <tag></tag>
   <elementGuidId>65ceef28-7a17-433c-95ce-5650dbd9f747</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='Name']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;Name&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6f03f026-eac9-494d-90b3-b1ce8740be8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Name</value>
      <webElementGuid>e50347d3-00de-4d09-aa9c-81c561559a7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2bd1da2e-8423-4fbe-bb1e-4d9f1a73528d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>46ed1940-73c0-46dc-b7cb-f6bd89646db0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>179289d8-98af-4630-bbe3-cb6f5db93f5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine ng-invalid igx-input-group__input ng-star-inserted</value>
      <webElementGuid>be2bfc9e-9f41-46fa-ad2c-f16674423168</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;igx-input-group-11&quot;)/div[@class=&quot;igx-input-group__bundle ng-star-inserted&quot;]/div[@class=&quot;igx-input-group__bundle-main&quot;]/input[@class=&quot;ng-untouched ng-pristine ng-invalid igx-input-group__input ng-star-inserted&quot;]</value>
      <webElementGuid>f9b0f076-afbe-4a17-8ae4-c6253ed5c4ad</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='Name']</value>
      <webElementGuid>ec5bcb17-5e37-45d5-a10d-4d3a10b19cfd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//igx-input-group[@id='igx-input-group-11']/div/div/input</value>
      <webElementGuid>93791844-eac3-4375-a6a5-0c743dbc35e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/igx-input-group/div/div/input</value>
      <webElementGuid>cc0ddb53-2d9c-4fe0-a4aa-44a843d8223e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'Name' and @type = 'text']</value>
      <webElementGuid>1e695b8f-4384-40b8-9a2e-84750b527be5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
