<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Description_Description</name>
   <tag></tag>
   <elementGuidId>b31ed484-3219-4c2e-a138-6a08a8c8a163</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@name='Description']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>textarea[name=&quot;Description&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>52f28677-8f69-41d7-bbbd-b7ba1fd55143</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>1500</value>
      <webElementGuid>b6bf8b72-051d-42c0-aaec-a96d75dab40d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Description</value>
      <webElementGuid>8f9d27c6-a907-4225-8f8d-7b4299485326</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6baecbec-e0c8-49fb-8848-4cde6fc2f4df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>dbf9be6f-1f48-48d8-9aeb-80cac3eb0b49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine ng-valid igx-input-group__textarea ng-star-inserted</value>
      <webElementGuid>383b4761-4234-4b0e-ae7e-12b6f471e449</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;igx-input-group-14&quot;)/div[@class=&quot;igx-input-group__bundle ng-star-inserted&quot;]/div[@class=&quot;igx-input-group__bundle-main&quot;]/textarea[@class=&quot;ng-untouched ng-pristine ng-valid igx-input-group__textarea ng-star-inserted&quot;]</value>
      <webElementGuid>63cc108f-dca9-4fee-ba70-f8c2a31b5f6a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@name='Description']</value>
      <webElementGuid>d590e6b1-70c2-41c1-9559-df2b4c91f134</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//igx-input-group[@id='igx-input-group-14']/div/div/textarea</value>
      <webElementGuid>cdb5ee0f-c8f3-405a-91b7-7091e76713c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//igx-input-group/div/div/textarea</value>
      <webElementGuid>adca9ab4-880b-4aa7-ad33-487e16861689</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'Description' and @type = 'text']</value>
      <webElementGuid>8777e7c9-fe0b-4e4b-9812-049adbd6ecd4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
