<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_CARRIER</name>
   <tag></tag>
   <elementGuidId>a2668868-83eb-44db-8caa-914de4d3707a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//igx-grid-cell[@id='FWLookupGrid_0_1']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.ng-star-inserted</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>55779a82-9e55-4c5a-9f2d-df0ac959c01d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/Information/Lookups/Edit/9783</value>
      <webElementGuid>5ccb35ec-110b-47f3-8f77-85916c338643</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-star-inserted</value>
      <webElementGuid>83881977-d6ae-4ad5-8de0-003fca2e174b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> CARRIER </value>
      <webElementGuid>58ef1b53-41cb-476b-b821-41e9b676b77b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;FWLookupGrid_0_1&quot;)/a[@class=&quot;ng-star-inserted&quot;]</value>
      <webElementGuid>bcd87547-18bc-4f95-a589-df0bdd3a042f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//igx-grid-cell[@id='FWLookupGrid_0_1']/a</value>
      <webElementGuid>7490a18e-537a-477a-b6fa-afd1c88e0cbf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'CARRIER')]</value>
      <webElementGuid>5e9b6313-8216-47eb-930a-27306d1f548d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sort Order'])[1]/following::a[1]</value>
      <webElementGuid>a0cd38a6-2917-4208-9c1e-1f36dd909f9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Is ReadOnly'])[1]/following::a[1]</value>
      <webElementGuid>4b59316d-80ad-4cae-b184-be80854a31ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Carrier'])[1]/preceding::a[1]</value>
      <webElementGuid>463d68f6-db73-4f95-9f98-105b9afaa994</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Company Type'])[1]/preceding::a[1]</value>
      <webElementGuid>94549979-c660-46db-8d34-d552efb267bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='CARRIER']/parent::*</value>
      <webElementGuid>1109f589-a354-441a-88ce-e5deef7e1825</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/Information/Lookups/Edit/9783')]</value>
      <webElementGuid>45bb40fa-0119-45ba-824e-48e8571516ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//igx-grid-cell/a</value>
      <webElementGuid>db2b5f4a-5b50-429f-86e3-1f0223776b05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/Information/Lookups/Edit/9783' and (text() = ' CARRIER ' or . = ' CARRIER ')]</value>
      <webElementGuid>3ec0276f-49f5-4927-a41b-93c1b910ffec</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
