<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Sign in</name>
   <tag></tag>
   <elementGuidId>1cbe1812-90fc-4df4-9286-4461cc54aec9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form/div[2]/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.btn-primary.btn-block.igx-button--flat</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>6e5fd4f7-823e-4989-ae0a-ab902ef40fa9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>igxbutton</name>
      <type>Main</type>
      <value>flat</value>
      <webElementGuid>5418dc98-f719-434f-8e27-a5e3e8bb3ce1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn-primary btn-block igx-button--flat</value>
      <webElementGuid>c61eeb63-591e-42b4-b58f-8b1e8701c0bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f883aec6-165c-49e7-b9f1-6acd857fd84b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Sign in </value>
      <webElementGuid>eec52116-2768-45d3-8e83-0057ddc2e03a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;ng-tns-0-0&quot;]/app-root[1]/app-auth-layout[1]/div[@class=&quot;app-auth-content h-100&quot;]/app-login-layout[1]/div[@class=&quot;login-wrap&quot;]/div[@class=&quot;login-inner page-content&quot;]/div[@class=&quot;content&quot;]/div[@class=&quot;login-form-wrap&quot;]/div[@class=&quot;login-form&quot;]/app-login[1]/div[1]/form[@class=&quot;ng-touched ng-dirty ng-valid&quot;]/div[@class=&quot;form-group&quot;]/button[@class=&quot;btn-primary btn-block igx-button--flat&quot;]</value>
      <webElementGuid>154abf7a-c8bd-4f6c-8aec-72ca0620536d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[2]/button</value>
      <webElementGuid>ebde7b13-d5d0-444f-90cd-36b4263690fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = ' Sign in ' or . = ' Sign in ')]</value>
      <webElementGuid>aa171a19-be82-4b5d-b1d7-2c37b8990f4b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
