<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Username  Email_Email</name>
   <tag></tag>
   <elementGuidId>4ccb308a-b9c8-4a9c-84c0-f6157c3a8145</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='Email']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;Email&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>427a9d43-fadd-4e64-a012-a9fb0c01aa2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Email</value>
      <webElementGuid>3b0d0ea4-a773-4873-b5dd-4d8c55647048</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>166e4344-e83d-409c-88a4-ac82787796b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>new-password</value>
      <webElementGuid>d51498d7-94fe-40d7-9b89-befaf3f007ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine igx-input-group__input ng-invalid</value>
      <webElementGuid>dc1260d3-4555-48e9-86af-67e02431c273</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;igx-input-group-0&quot;)/div[@class=&quot;igx-input-group__bundle&quot;]/div[@class=&quot;igx-input-group__bundle-main&quot;]/input[@class=&quot;ng-untouched ng-pristine igx-input-group__input ng-invalid&quot;]</value>
      <webElementGuid>ba605dfe-334f-4fdb-8724-2409564b795f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='Email']</value>
      <webElementGuid>e5893797-d6ce-497a-9216-4cb4a120f3f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//igx-input-group[@id='igx-input-group-0']/div/div/input</value>
      <webElementGuid>4e92290b-51cf-48bd-ac3f-56765272c148</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>fd58b684-9392-482b-b338-d44ebf13506d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'Email' and @type = 'text']</value>
      <webElementGuid>3c326870-c13e-4b36-b35c-34c00ed5eeac</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
